### ISSUE TITLE
Programming

### ISSUE THREAD

**Issue by roy-sukrit** [MarkYHZhang/MidiBach#1]
Hi sir even i am trying to make a program like synthesia i have experience of  OOP Java,  i couldn't find a way to approach the project can you give me any suggestions sir? It would be a great help .

**Comment by MarkYHZhang** [comment]
Maybe you could be a bit more specific for your question? Well I started by first figuring out how to read midi input from USB and how to interpret and parse those signals. Then, I figured out how to render it on the screen based on how long each note is being pressed.

**Comment by roy-sukrit** [comment]
I am using .net library called midi dot net to read midi signals from usb , was trying to find a way to render on screen the usb midi or any midi file.

**Comment by MarkYHZhang** [comment]
I have no experience with .net, so if you have questions regarding Java I can help. Also note that for Java, it has midi capabilities built in without any external libraries so that might actually be easier/reliable.

**Comment by MarkYHZhang** [comment]
Closed due to inactivity
